### ISSUE TITLE
Linking CXX executable - Mac

### ISSUE THREAD

**Issue by cauribe** [SebastianSchlag/kahypar#32]
Hi all,

I am a beginner as far as the c++ mac world, and am having a very similar issue to [https://github.com/SebastianSchlag/kahypar/issues/19#issue-281404025] with linking CXX executable and boost. He has some of the details worded better than I could explain so I have referenced that issue. I have the same system specifications, and have downloaded boost using both brew and macports as well. However, the system I am trying to run must be compiled (and has been compiled by others) using c++98, not c++11. I have tried 

`set CMAKE_CXX_FLAGS -std=c++98` 

and then compiled using

`make -j 4`

some of the errors I have include:

ld: warning: -L path '/usr/local/lib/libgsl.dylib' is not a directory
Undefined symbols for architecture x86_64:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [samos] Error 1
make[1]: *** [src/CMakeFiles/samos.dir/all] Error 2
make: *** [all] Error 2

Does anyone have any additional information/advice for how to approach this problem? Thanks.

**Comment by SebastianSchlag** [comment]
Hi,

> d: warning: -L path '/usr/local/lib/libgsl.dylib' is not a directory
Undefined symbols for architecture x86_64:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [samos] Error 1
make[1]: *** [src/CMakeFiles/samos.dir/all] Error 2
make: *** [all] Error 2

These errors do not seem to be related to KaHyPar. Are you actually trying to built KaHyPar or some other project?

> ld: warning: -L path '/usr/local/lib/libgsl.dylib' is not a directory

As this warning indicates, there is something wrong with your linker flags. Maybe just use "/usr/local/lib/"?

**Comment by cauribe** [comment]
This is for another project but the setup for compiling appeared very similar to a previous issue so I was hoping to implement some of the same concepts to the errors. 

What exactly is the -L path, does that describe all of the libraries, and this particular warning is for the gsl library?

**Comment by cauribe** [comment]
This is for another project but the setup for compiling appeared very similar to a previous issue so I was hoping to implement some of the same concepts to the errors.

Is the -L path exclusive to the gsl library it is trying to refer to or does that describe any path I am trying to use?

**Comment by SebastianSchlag** [comment]
In general -L should refer to the path where the libraries are located.

I just had a quick look at your repository. If you're trying to build SAMoS I would suggest that you open an issue at the main repository: https://github.com/sknepneklab/SAMoS
Especially since they already mention problems with dependencies installed via homebrew:

> WARNING: Some Mac users have reported problems with compiling SAMoS on Sierra and High Sierra using packages installed with 'brew'. Switching to 
the 'MacPorts' seems to solve the problem.
