### ISSUE TITLE
block size not match, bug or incorrect using?

### ISSUE THREAD

**Issue by a8156268** [SebastianSchlag/kahypar#37]
I did a partitioning on my graph, and got a result. </br>
I tried to check the correctness of partitioning result, and found something wrong.</br>
First, I directly got the block weight information from the partitioning result that KaHyPar outputted on the console.</br>
Then, for each block(according to Partition File), I manual summed weight of all vertices in that block.</br>
Unfortunately, I found preceding two weights were not matched.</br>
The table below shows the difference:

|  index  |    from console   | manual summed |
| ------- | ----------------- | ------------- |
| part  0 | w(  0 ) = 8056461 | w =  4370837  |
| part  1 | w(  1 ) = 8083478 | w = 14302264  |
| part  2 | w(  2 ) = 6445754 | w =  2117552  |
| part  3 | w(  3 ) = 6659848 | w =  2686193  |
| part  4 | w(  4 ) = 8081908 | w =  9015610  |
| part  5 | w(  5 ) = 3284632 | w =   223157  |
| part  6 | w(  6 ) = 7752835 | w =  1500391  |
| part  7 | w(  7 ) = 8081145 | w = 17349691  |
| part  8 | w(  8 ) = 8072179 | w =  6118026  |
| part  9 | w(  9 ) = 7892213 | w =  4591978  |
| part 10 | w( 10 ) = 8077959 | w = 23184113  |
| part 11 | w( 11 ) = 7424514 | w =  3071367  |
| part 12 | w( 12 ) = 8053980 | w = 17117247  |
| part 13 | w( 13 ) = 7102451 | w =  5421560  |
| part 14 | w( 14 ) = 7487524 | w =  2910723  |
| part 15 | w( 15 ) = 7033688 | w =  3595229  |

Other information:
command line:
`./KaHyPar -h ~/graph -k 16 -e 0.10 -o km1 -m direct -p ../../../config/km1_direct_kway_sea18.ini -v on`
Graph meta information:
```
******************************************************************************** 
*                                    Input                                     * 
******************************************************************************** 
Hypergraph Information 
Name : countries.2019-05-16.carrier 
Type: edgeWeights=true nodeWeights=true 
# HNs : 47986 # HEs : 29502 # pins: 1971962 
HE size             HE weight           HN degree           HN weight 
| min= 0            | min= 0            | min= 0            | min= 0           
| Q1 = 4            | Q1 = 118          | Q1 = 14           | Q1 = 0           
| med= 16           | med= 375          | med= 30           | med= 102         
| Q3 = 50           | Q3 = 1336         | Q3 = 57           | Q3 = 578         
| max= 2086         | max= 2469924      | max= 277          | max= 2469924     
| avg= 66.8416      | avg= 3971.84      | avg= 41.0945      | avg= 2450.52     
| sd = 158.885      | sd = 28399.8      | sd = 37.0743      | sd = 28464.9     

******************************************************************************** 
*                          Top Level Preprocessing..                           * 
******************************************************************************** 
 Removed 2701 hyperedges with |e|=1  
 ===> 33 unconnected HNs could have been removed  
Performing community detection: 
  hypergraph is a graph = false 
  # communities         = 166 
  modularity            = 0.818004 
```
Graph file could be find at: https://github.com/a8156268/graph/blob/master/graph_info.
It is in the format of hMetis.
Was there something I did wrong? Or there is a bug in KaHyPar?

**Comment by SebastianSchlag** [comment]
Hi,
thanks for reporting this. I think I've found the issue.
Our hMetis file parser only ignored comments at the head of the file. Comment lines starting with '%' that appeared somewhere within the file (as in your hypergraph) were not ignored.
Commit 6d5cf8565a060f5844f4a96ad220f5dc1254c0b2 now fixes this.

Could you please double-check if that solves your problem?

**Comment by a8156268** [comment]
Thank you for quickly responding.
I've checked this by two ways.
- i. Removing '%' lines from my hypergraph file.
- ii. Applying your path and recompiling KaHyPar, without removing '%' lines.

Both the two ways work well. I got correct result. 
Thank you again.
