### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by veyseler-su** [SebastianSchlag/kahypar#40]
Hi I am having troubles with building KaHyPar on Linux system.

Currently I am using 
CentOS 6.5 x86_64
g++ 5.3.0
Cmake 3.14.5 
Boost 1.70.0 

Thanks for any help !

Error I am getting 
-While cloning the repo

![image](https://user-images.githubusercontent.com/46130236/59617889-cf5d4f00-912f-11e9-9131-7db84cde58e7.png)

**Comment by veyseler-su** [comment]
I solved the issue with downloading the repo as a zip file and then exclusively copying the contents of the google test from the link below.
https://github.com/google/googletest

**Comment by SebastianSchlag** [comment]
Hi,
this seems weird. It's actually not a build errror. It seems that you have problems cloning googletest from https://github.com/google/googletest.git.
Thanks for the update that downloading the zip file worked.  are you able to clone it directly via

`` git clone https://github.com/google/googletest.git  `` ?

**Comment by veyseler-su** [comment]
Nope :( I had to download google test as a zip file too. But now I am having another issue related to boost options library.
All of the errors look like this.
**kahypar.cc:(.text+0xbc91): undefined reference to `boost::program_options::options_description::m_default_line_length'**

**Comment by SebastianSchlag** [comment]
Do you have /path/to/boost in your $PATH?

**Comment by veyseler-su** [comment]
I have been trying to build for last 10 hours straight but no matter what I do I couldn't do it.

Here is the result from echo $PATH command.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/46130236/59677949-d3db4380-91d3-11e9-9470-10e5630e9d8b.png">

Here is the whole output of the Cmake command 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/46130236/59678070-1bfa6600-91d4-11e9-98b9-177abd6b832e.png">

problem is still the same as above. I am sorry I am not familiar with Cmake. I couldn't solve It on my own by simply googling it :)

thanks !

**Comment by SebastianSchlag** [comment]
It looks like you got two different versions of boost installed:

![boost_17](https://user-images.githubusercontent.com/484403/59679992-97f2af00-91d0-11e9-8d11-d60dfe760410.png)

This is the boost version you refer to and it seems to be configured correctly.

However, right after that, you see the following: 

![boost_148](https://user-images.githubusercontent.com/484403/59680029-ac36ac00-91d0-11e9-983e-b64dc404cbae.png)

For this boost version, cmake does not find the include dirs and library dirs etc.

I would assume that this is the root cause of your problem. Could you try and uninstall the old boost version?

**Comment by veyseler-su** [comment]
Unfortunately I am not allowed to do this kind of operation on that machine. I also tried to build with my own computer and it succeeded. 

I hoped that I can set these parameters(boost include, boost library dirs, boost libraries) manually but I couldn't. I tried many things but none of them worked.

**Comment by veyseler-su** [comment]
Now I can run KaHyPar :) It took me lots of hours to figure out but one can directly specify it's boost path like below. Thanks for your help :)
<img width="662" alt="image" src="https://user-images.githubusercontent.com/46130236/59682273-8c0de980-91de-11e9-9ee9-e89d167233a0.png">
