### ISSUE TITLE
Return error codes reference

### ISSUE THREAD

**Issue by jcmgray** [SebastianSchlag/kahypar#45]
Hello, thanks for this great project! I'm sure it's somewhere in the source but I can't quite find it - what do the different return error codes mean? Currently I'm getting ``KaHyPar failed with -4`` semi regularly on some cluster nodes and its a bit hard to debug since I can't reproduce locally.

**Comment by SebastianSchlag** [comment]
Hi,
unfortunately KaHyPar doesn't really have systematic return error codes. We basically just use std::exit(-1) in case the framework is somehow misconfigured. In most cases, this happens if config parameters are specified incorrectly.
 I've just 'greped' through the code to see whether we return -4 somewhere, but did not find any occurrences.
What kind of system / compiler are you using?

**Comment by jcmgray** [comment]
It's a batch linux system and I compiled KaHyPar with gcc 8.2. I've been actually been calling KaHyPar from python directly using ``subprocess.Popen`` and temporary files to pass the graphs in, and I wonder if there is some bad interaction when doing this on shared filesystem with many many processes in parallel.

In any case, I see you have just added a python wrapper (great!) which is a much preferable option that I'll try now. Do you have any immediate plans to add weighted edges (/nodes) to the interface? Maybe it is already possible?

**Comment by SebastianSchlag** [comment]
Good point. I missed that when creating the pybind bindings.
I have updated the interface to allow the construction of weighted hypergraphs (see: https://github.com/SebastianSchlag/kahypar/commit/d50d9c041599c02fc42882c3661f63eaf1bebcfb).

**Comment by jcmgray** [comment]
Amazing, thanks! That seems to be working well locally, hopefully will work better on the cluster as well, in which case I'll close this.

One final (and pretty inconsequential) comment on the python interface: every time a hypergraph is created/partitioned the message "No filename for partition file specified" is logged. Not really a big problem but clutters the output if you are performing a lot of partitions!

**Comment by SebastianSchlag** [comment]
Alright. If it still occasionally fails we'll dig deeper into the issue.

Good point. I removed the log message in commit https://github.com/SebastianSchlag/kahypar/commit/753655d89881d469d1df6547e7fb77e1c886ac2c and updated the pypi package.

**Comment by jcmgray** [comment]
I don't seem to be encountering this error with the new python interface - thanks very much for the rapid responses/updates.
