### ISSUE TITLE
Python windows install unicode error

### ISSUE THREAD

**Issue by jcmgray** [SebastianSchlag/kahypar#48]
When installing the kahypar python interface on windows, a unicode error is raised when ``long_description`` is set from the ``README.md``.

This should be easily fixed (in `setup.py`) with :
```python
with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()
```
Though note that that this is a python 3 only keyword argument.

**Comment by SebastianSchlag** [comment]
Thanks for pointing this out. 
This should now be fixed with commit https://github.com/SebastianSchlag/kahypar/commit/d0f08ebaad1f60db9006d25b5bc4cce837464fcc.
